services:
  docker-roonserver:
    image: ghcr.io/noahimesaka1873/roonserver:latest
    container_name: docker-roonserver
    hostname: Oomuro-ke # Change to your choice of hostname
    network_mode: host
    environment:
      TZ: "Asia/Seoul" # Change to your timezone
    volumes:
      - ./app:/app
      - ./data:/data
      - ./music:/music
      - ./backups:/backup
  hqplayer:
    network_mode: host
    image: ghcr.io/noahimesaka1873/hqplayer5:latest
    build: ./hqplayer-docker5
    restart: always
    volumes:
      - ./hqplayer:/etc/hqplayer
    devices:
    - /dev/bus/usb:/dev/bus/usb # You MUST pass through /dev/bus/usb or else HQPlayer **WILL** segfault.
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    environment:
      TZ: "Asia/Seoul" # Also change to your timezone
